export { Instance } from "./text/instance.js";
export { Value } from "./text/value.js";
export { Direction } from "./text/direction.js";
export * as Dictionary from "./text/dictionary.js";
export * as Line from "./text/line.js";
export * as Segment from "./text/segment.js";
export * as Item from "./text/item.js";
export * as Part from "./text/part.js";
export * as Split from "./text/split.js";
