export var Order;
(function (Order) {
    Order[Order["BOOKS_LANGUAGES_VERSIONS"] = 0] = "BOOKS_LANGUAGES_VERSIONS";
    Order[Order["BOOKS_VERSIONS_LANGUAGES"] = 1] = "BOOKS_VERSIONS_LANGUAGES";
    Order[Order["LANGUAGES_BOOKS_VERSIONS"] = 2] = "LANGUAGES_BOOKS_VERSIONS";
    Order[Order["LANGUAGES_VERSIONS_BOOKS"] = 3] = "LANGUAGES_VERSIONS_BOOKS";
    Order[Order["VERSIONS_BOOKS_LANGUAGES"] = 4] = "VERSIONS_BOOKS_LANGUAGES";
    Order[Order["VERSIONS_LANGUAGES_BOOKS"] = 5] = "VERSIONS_LANGUAGES_BOOKS";
})(Order || (Order = {}));
