import * as Language from "../../../model/language.js";

import { Key } from "../../key.js";

import * as Layout from "../instance.js";
import * as Space from "../space.js";

import * as Common from "./common.js";

const OXIA_AND_VARIA: Space.Combo = [
    [Common.OXIA_AND_VARIA_KEY],
    [
        // U+1FFD GREEK OXIA
        [[Common.OXIA_AND_VARIA_KEY], `´`, false],

        // U+1F71 GREEK SMALL LETTER ALPHA WITH OXIA,
        // U+1FBB GREEK CAPITAL LETTER ALPHA WITH OXIA
        [[Key.KEY_A], `ά`, `Ά`],
        // U+1F73 GREEK SMALL LETTER EPSILON WITH OXIA,
        // U+1FC9 GREEK CAPITAL LETTER EPSILON WITH OXIA
        [[Key.KEY_E], `έ`, `Έ`],
        // U+1F75 GREEK SMALL LETTER ETA WITH OXIA,
        // U+1FCB GREEK CAPITAL LETTER ETA WITH OXIA
        [[Key.KEY_H], `ή`, `Ή`],
        // U+1F77 GREEK SMALL LETTER IOTA WITH OXIA,
        // U+1FDB GREEK CAPITAL LETTER IOTA WITH OXIA
        [[Key.KEY_I], `ί`, `Ί`],
        // U+1F79 GREEK SMALL LETTER OMICRON WITH OXIA,
        // U+1FF9 GREEK CAPITAL LETTER OMICRON WITH OXIA
        [[Key.KEY_O], `ό`, `Ό`],
        // U+1F7B GREEK SMALL LETTER UPSILON WITH OXIA,
        // U+1FEB GREEK CAPITAL LETTER UPSILON WITH OXIA
        [[Key.KEY_U], `ύ`, `Ύ`],
        // U+1F7D GREEK SMALL LETTER OMEGA WITH OXIA,
        // U+1FFB GREEK CAPITAL LETTER OMEGA WITH OXIA
        [[Key.KEY_V], `ώ`, `Ώ`],
    ],
    [
        // U+1FEF GREEK VARIA
        [[Common.OXIA_AND_VARIA_KEY], ```, false],

        // U+1F70 GREEK SMALL LETTER ALPHA WITH VARIA,
        // U+1FBA GREEK CAPITAL LETTER ALPHA WITH VARIA
        [[Key.KEY_A], `ὰ`, `Ὰ`],
        // U+1F72 GREEK SMALL LETTER EPSILON WITH VARIA,
        // U+1FC8 GREEK CAPITAL LETTER EPSILON WITH VARIA
        [[Key.KEY_E], `ὲ`, `Ὲ`],
        // U+1F74 GREEK SMALL LETTER ETA WITH VARIA,
        // U+1FCA GREEK CAPITAL LETTER ETA WITH VARIA
        [[Key.KEY_H], `ὴ`, `Ὴ`],
        // U+1F76 GREEK SMALL LETTER IOTA WITH VARIA,
        // U+1FDA GREEK CAPITAL LETTER IOTA WITH VARIA
        [[Key.KEY_I], `ὶ`, `Ὶ`],
        // U+1F78 GREEK SMALL LETTER OMICRON WITH VARIA,
        // U+1FF8 GREEK CAPITAL LETTER OMICRON WITH VARIA
        [[Key.KEY_O], `ὸ`, `Ὸ`],
        // U+1F7A GREEK SMALL LETTER UPSILON WITH VARIA,
        // U+1FEA GREEK CAPITAL LETTER UPSILON WITH VARIA
        [[Key.KEY_U], `ὺ`, `Ὺ`],
        // U+1F7C GREEK SMALL LETTER OMEGA WITH VARIA,
        // U+1FFA GREEK CAPITAL LETTER OMEGA WITH VARIA
        [[Key.KEY_V], `ὼ`, `Ὼ`],
    ],
];

const PERISPOMENI_AND_DIALYTIKA: Space.Combo = [
    [Common.PERISPOMENI_AND_DIALYTIKA_KEY],
    [
        // U+1FC0 GREEK PERISPOMENI
        [[Common.PERISPOMENI_AND_DIALYTIKA_KEY], `῀`, false],

        // U+1FB6 GREEK SMALL LETTER ALPHA WITH PERISPOMENI
        [[Key.KEY_A], `ᾶ`, false],
        // U+1FC6 GREEK SMALL LETTER ETA WITH PERISPOMENI
        [[Key.KEY_H], `ῆ`, false],
        // U+1FD6 GREEK SMALL LETTER IOTA WITH PERISPOMENI
        [[Key.KEY_I], `ῖ`, false],
        // U+1FE6 GREEK SMALL LETTER UPSILON WITH PERISPOMENI
        [[Key.KEY_U], `ῦ`, false],
        // U+1FF6 GREEK SMALL LETTER OMEGA WITH PERISPOMENI
        [[Key.KEY_V], `ῶ`, false],
    ],
    [
        // U+00A8 DIAERESIS
        [[Common.PERISPOMENI_AND_DIALYTIKA_KEY], `¨`, false],

        // U+03CA GREEK SMALL LETTER IOTA WITH DIALYTIKA,
        // U+03AA GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
        [[Key.KEY_I], `ϊ`, `Ϊ`],
        // U+03CB GREEK SMALL LETTER UPSILON WITH DIALYTIKA,
        // U+03AB GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
        [[Key.KEY_U], `ϋ`, `Ϋ`],
    ],
];

const PSILI_AND_DASIA: Space.Combo = [
    [Common.PSILI_AND_DASIA_KEY],
    [
        // U+1FBF GREEK PSILI 
        [[Common.PSILI_AND_DASIA_KEY], `᾿`, false],

        // U+1F00 GREEK SMALL LETTER ALPHA WITH PSILI,
        // U+1F08 GREEK CAPITAL LETTER ALPHA WITH PSILI
        [[Key.KEY_A], `ἀ`, `Ἀ`],
        // U+1F10 GREEK SMALL LETTER EPSILON WITH PSILI,
        // U+1F18 GREEK CAPITAL LETTER EPSILON WITH PSILI
        [[Key.KEY_E], `ἐ`, `Ἐ`],
        // U+1F20 GREEK SMALL LETTER ETA WITH PSILI,
        // U+1F28 GREEK CAPITAL LETTER ETA WITH PSILI
        [[Key.KEY_H], `ἠ`, `Ἠ`],
        // U+1F30 GREEK SMALL LETTER IOTA WITH PSILI,
        // U+1F38 GREEK CAPITAL LETTER IOTA WITH PSILI
        [[Key.KEY_I], `ἰ`, `Ἰ`],
        // U+1F40 GREEK SMALL LETTER OMICRON WITH PSILI,
        // U+1F48 GREEK CAPITAL LETTER OMICRON WITH PSILI
        [[Key.KEY_O], `ὀ`, `Ὀ`],
        // U+1F50 GREEK SMALL LETTER UPSILON WITH PSILI
        [[Key.KEY_U], `ὐ`, false],
        // U+1F60 GREEK SMALL LETTER OMEGA WITH PSILI,
        // U+1F68 GREEK CAPITAL LETTER OMEGA WITH PSILI
        [[Key.KEY_V], `ὠ`, `Ὠ`],
        // U+1FE4 GREEK SMALL LETTER RHO WITH PSILI
        [[Key.KEY_R], `ῤ`, false],
    ],
    [
        // U+1FFE GREEK DASIA
        [[Common.PSILI_AND_DASIA_KEY], `῾`, false],

        // U+1F01 GREEK SMALL LETTER ALPHA WITH DASIA,
        // U+1F09 GREEK CAPITAL LETTER ALPHA WITH DASIA
        [[Key.KEY_A], `ἁ`, `Ἁ`],
        // U+1F11 GREEK SMALL LETTER EPSILON WITH DASIA,
        // U+1F19 GREEK CAPITAL LETTER EPSILON WITH DASIA
        [[Key.KEY_E], `ἑ`, `Ἑ`],
        // U+1F21 GREEK SMALL LETTER ETA WITH DASIA,
        // U+1F29 GREEK CAPITAL LETTER ETA WITH DASIA
        [[Key.KEY_H], `ἡ`, `Ἡ`],
        // U+1F31 GREEK SMALL LETTER IOTA WITH DASIA,
        // U+1F39 GREEK CAPITAL LETTER IOTA WITH DASIA
        [[Key.KEY_I], `ἱ`, `Ἱ`],
        // U+1F41 GREEK SMALL LETTER OMICRON WITH DASIA,
        // U+1F49 GREEK CAPITAL LETTER OMICRON WITH DASIA
        [[Key.KEY_O], `ὁ`, `Ὁ`],
        // U+1F51 GREEK SMALL LETTER UPSILON WITH DASIA,
        // U+1F59 GREEK CAPITAL LETTER UPSILON WITH DASIA
        [[Key.KEY_U], `ὑ`, `Ὑ`],
        // U+1F61 GREEK SMALL LETTER OMEGA WITH DASIA,
        // U+1F69 GREEK CAPITAL LETTER OMEGA WITH DASIA
        [[Key.KEY_V], `ὡ`, `Ὡ`],
        // U+1FE5 GREEK SMALL LETTER RHO WITH DASIA,
        // U+1FEC GREEK CAPITAL LETTER RHO WITH DASIA
        [[Key.KEY_R], `ῥ`, `Ῥ`],
    ],
];

const PSILI_OXIA_AND_DASIA_OXIA: Space.Combo = [
    [Common.PSILI_OXIA_AND_DASIA_OXIA_KEY],
    [
        // U+1FCE GREEK PSILI AND OXIA
        [[Common.PSILI_OXIA_AND_DASIA_OXIA_KEY], `῎`, false],

        // U+1F04 GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA,
        // U+1F0C GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
        [[Key.KEY_A], `ἄ`, `Ἄ`],
        // U+1F14 GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA,
        // U+1F1C GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
        [[Key.KEY_E], `ἔ`, `Ἔ`],
        // U+1F24 GREEK SMALL LETTER ETA WITH PSILI AND OXIA,
        // U+1F2C GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
        [[Key.KEY_H], `ἤ`, `Ἤ`],
        // U+1F34 GREEK SMALL LETTER IOTA WITH PSILI AND OXIA,
        // U+1F3C GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
        [[Key.KEY_I], `ἴ`, `Ἴ`],
        // U+1F44 GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA,
        // U+1F4C GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
        [[Key.KEY_O], `ὄ`, `Ὄ`],
        // U+1F54 GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
        [[Key.KEY_U], `ὔ`, false],
        // U+1F64 GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA,
        // U+1F6C GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
        [[Key.KEY_V], `ὤ`, `Ὤ`],
    ],
    [
        // U+1FDE GREEK DASIA AND OXIA
        [[Common.PSILI_OXIA_AND_DASIA_OXIA_KEY], `῞`, false],

        // U+1F05 GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA,
        // U+1F0D GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
        [[Key.KEY_A], `ἅ`, `Ἅ`],
        // U+1F15 GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA,
        // U+1F1D GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
        [[Key.KEY_E], `ἕ`, `Ἕ`],
        // U+1F25 GREEK SMALL LETTER ETA WITH DASIA AND OXIA,
        // U+1F2D GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
        [[Key.KEY_H], `ἥ`, `Ἥ`],
        // U+1F35 GREEK SMALL LETTER IOTA WITH DASIA AND OXIA,
        // U+1F3D GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
        [[Key.KEY_I], `ἵ`, `Ἵ`],
        // U+1F45 GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA,
        // U+1F4D GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
        [[Key.KEY_O], `ὅ`, `Ὅ`],
        // U+1F55 GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA,
        // U+1F5D GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
        [[Key.KEY_U], `ὕ`, `Ὕ`],
        // U+1F65 GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA,
        // U+1F6D GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
        [[Key.KEY_V], `ὥ`, `Ὥ`],
    ],
];

const PSILI_VARIA_AND_DASIA_VARIA: Space.Combo = [
    [Common.PSILI_VARIA_AND_DASIA_VARIA_KEY],
    [
        // U+1FCD GREEK PSILI AND VARIA
        [[Common.PSILI_VARIA_AND_DASIA_VARIA_KEY], `῍`, false],

        // U+1F02 GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA,
        // U+1F0A GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
        [[Key.KEY_A], `ἂ`, `Ἂ`],
        // U+1F12 GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA,
        // U+1F1A GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
        [[Key.KEY_E], `ἒ`, `Ἒ`],
        // U+1F22 GREEK SMALL LETTER ETA WITH PSILI AND VARIA,
        // U+1F2A GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
        [[Key.KEY_H], `ἢ`, `Ἢ`],
        // U+1F32 GREEK SMALL LETTER IOTA WITH PSILI AND VARIA,
        // U+1F3A GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
        [[Key.KEY_I], `ἲ`, `Ἲ`],
        // U+1F42 GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA,
        // U+1F4A GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
        [[Key.KEY_O], `ὂ`, `Ὂ`],
        // U+1F52 GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
        [[Key.KEY_U], `ὒ`, false],
        // U+1F62 GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA,
        // U+1F6A GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
        [[Key.KEY_V], `ὢ`, `Ὢ`],
    ],
    [
        // U+1FDD GREEK DASIA AND VARIA
        [[Common.PSILI_VARIA_AND_DASIA_VARIA_KEY], `῝`, false],

        // U+1F03 GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA,
        // U+1F0B GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
        [[Key.KEY_A], `ἃ`, `Ἃ`],
        // U+1F13 GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA,
        // U+1F1B GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
        [[Key.KEY_E], `ἓ`, `Ἓ`],
        // U+1F23 GREEK SMALL LETTER ETA WITH DASIA AND VARIA,
        // U+1F2B GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
        [[Key.KEY_H], `ἣ`, `Ἣ`],
        // U+1F33 GREEK SMALL LETTER IOTA WITH DASIA AND VARIA,
        // U+1F3B GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
        [[Key.KEY_I], `ἳ`, `Ἳ`],
        // U+1F43 GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA,
        // U+1F4B GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
        [[Key.KEY_O], `ὃ`, `Ὃ`],
        // U+1F53 GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA,
        // U+1F5B GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
        [[Key.KEY_U], `ὓ`, `Ὓ`],
        // U+1F63 GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA,
        // U+1F6B GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
        [[Key.KEY_V], `ὣ`, `Ὣ`],
    ],
];

const PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI: Space.Combo = [
    [Common.PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI_KEY],
    [
        // U+1FCF GREEK PSILI AND PERISPOMENI
        [[Common.PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI_KEY], `῏`, false],

        // U+1F06 GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI,
        // U+1F0E GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
        [[Key.KEY_A], `ἆ`, `Ἆ`],
        // U+1F26 GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI,
        // U+1F2E GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
        [[Key.KEY_H], `ἦ`, `Ἦ`],
        // U+1F36 GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI,
        // U+1F3E GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
        [[Key.KEY_I], `ἶ`, `Ἶ`],
        // U+1F56 GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
        [[Key.KEY_U], `ὖ`, false],
        // U+1F66 GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI,
        // U+1F6E GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
        [[Key.KEY_V], `ὦ`, `Ὦ`],
    ],
    [
        // U+1FDF GREEK DASIA AND PERISPOMENI
        [[Common.PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI_KEY], `῟`, false],

        // U+1F07 GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI,
        // U+1F0F GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
        [[Key.KEY_A], `ἇ`, `Ἇ`],
        // U+1F27 GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI,
        // U+1F2F GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
        [[Key.KEY_H], `ἧ`, `Ἧ`],
        // U+1F37 GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI,
        // U+1F3F GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
        [[Key.KEY_I], `ἷ`, `Ἷ`],
        // U+1F57 GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI,
        // U+1F5F GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
        [[Key.KEY_U], `ὗ`, `Ὗ`],
        // U+1F67 GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI,
        // U+1F6F GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
        [[Key.KEY_V], `ὧ`, `Ὧ`],
    ],
];

const DIALYTIKA_OXIA_AND_DIALYTIKA_VARIA: Space.Combo = [
    [Common.DIALYTIKA_OXIA_AND_DIALYTIKA_VARIA_KEY],
    [
        // U+1FEE GREEK DIALYTIKA AND OXIA
        [[Common.DIALYTIKA_OXIA_AND_DIALYTIKA_VARIA_KEY], `΅`, false],

        // U+1FD3 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
        [[Key.KEY_I], `ΐ`, false],
        // U+1FE3 GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
        [[Key.KEY_U], `ΰ`, false],
    ],
    [
        // U+1FED GREEK DIALYTIKA AND VARIA
        [[Common.DIALYTIKA_OXIA_AND_DIALYTIKA_VARIA_KEY], `῭`, false],

        // U+1FD2 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
        [[Key.KEY_I], `ῒ`, false],
        // U+1FE2 GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
        [[Key.KEY_U], `ῢ`, false],
    ],
];

const DIALYTIKA_PERISPOMENI: Space.Combo = [
    [Common.DIALYTIKA_PERISPOMENI_KEY],
    [
        // U+1FC1 GREEK DIALYTIKA AND PERISPOMENI
        [[Common.DIALYTIKA_PERISPOMENI_KEY], `῁`, false],

        // U+1FD7 GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
        [[Key.KEY_I], `ῗ`, false],
        // U+1FE7 GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
        [[Key.KEY_U], `ῧ`, false],
    ],
    true,
];

const IOTA: Space.Combo = [
    [Common.IOTA_KEY],
    [
        // U+037A GREEK YPOGEGRAMMENI,
        // U+1FBE GREEK PROSGEGRAMMENI
        [[Common.IOTA_KEY], `ͺ`, `ι`],

        // U+1FB3 GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI,
        // U+1FBC GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
        [[Key.KEY_A], `ᾳ`, `ᾼ`],
        // U+1FC3 GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI,
        // U+1FCC GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
        [[Key.KEY_H], `ῃ`, `ῌ`],
        // U+1FF3 GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI,
        // U+1FFC GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
        [[Key.KEY_V], `ῳ`, `ῼ`],
    ],
    true,
];

const OXIA_IOTA_AND_VARIA_IOTA: Space.Combo = [
    [Common.OXIA_AND_VARIA_KEY],
    [
        // U+1FB4 GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
        [[Key.KEY_A], `ᾴ`, false],
        // U+1FC4 GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
        [[Key.KEY_H], `ῄ`, false],
        // U+1FF4 GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
        [[Key.KEY_V], `ῴ`, false],
    ],
    [
        // U+1FB2 GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
        [[Key.KEY_A], `ᾲ`, false],
        // U+1FC2 GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
        [[Key.KEY_H], `ῂ`, false],
        // U+1FF2 GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
        [[Key.KEY_V], `ῲ`, false],
    ],
];

const PERISPOMENI_IOTA: Space.Combo = [
    [Common.PERISPOMENI_AND_DIALYTIKA_KEY],
    [
        // U+1FB7 GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
        [[Key.KEY_A], `ᾷ`, false],
        // U+1FC7 GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
        [[Key.KEY_H], `ῇ`, false],
        // U+1FF7 GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
        [[Key.KEY_V], `ῷ`, false],
    ],
    false,
];

const PSILI_IOTA_AND_DASIA_IOTA: Space.Combo = [
    [Common.PSILI_AND_DASIA_KEY],
    [
        // U+1F80 GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI,
        // U+1F88 GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾀ`, `ᾈ`],
        // U+1F90 GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI,
        // U+1F98 GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾐ`, `ᾘ`],
        // U+1FA0 GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI,
        // U+1FA8 GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾠ`, `ᾨ`],
    ],
    [
        // U+1F81 GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI,
        // U+1F89 GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾁ`, `ᾉ`],
        // U+1F91 GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI,
        // U+1F99 GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾑ`, `ᾙ`],
        // U+1FA1 GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI,
        // U+1FA9 GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾡ`, `ᾩ`],
    ],
];

const PSILI_OXIA_IOTA_AND_DASIA_OXIA_IOTA: Space.Combo = [
    [Common.PSILI_OXIA_AND_DASIA_OXIA_KEY],
    [
        // U+1F84 GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI,
        // U+1F8C GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾄ`, `ᾌ`],
        // U+1F94 GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI,
        // U+1F9C GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾔ`, `ᾜ`],
        // U+1FA4 GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI,
        // U+1FAC GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾤ`, `ᾬ`],
    ],
    [
        // U+1F85 GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI,
        // U+1F8D GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾅ`, `ᾍ`],
        // U+1F95 GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI,
        // U+1F9D GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾕ`, `ᾝ`],
        // U+1FA5 GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI,
        // U+1FAD GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾥ`, `ᾭ`],
    ],
];

const PSILI_VARIA_IOTA_AND_DASIA_VARIA_IOTA: Space.Combo = [
    [Common.PSILI_VARIA_AND_DASIA_VARIA_KEY],
    [
        // U+1F82 GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI,
        // U+1F8A GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾂ`, `ᾊ`],
        // U+1F92 GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI,
        // U+1F9A GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾒ`, `ᾚ`],
        // U+1FA2 GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI,
        // U+1FAA GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾢ`, `ᾪ`],
    ],
    [
        // U+1F83 GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI,
        // U+1F8B GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾃ`, `ᾋ`],
        // U+1F93 GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI,
        // U+1F9B GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾓ`, `ᾛ`],
        // U+1FA3 GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI,
        // U+1FAB GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾣ`, `ᾫ`],
    ],
];

const PSILI_PERISPOMENI_IOTA_AND_DASIA_PERISPOMENI_IOTA: Space.Combo = [
    [Common.PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI_KEY],
    [
        // U+1F86 GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1F8E GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾆ`, `ᾎ`],
        // U+1F96 GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1F9E GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾖ`, `ᾞ`],
        // U+1FA6 GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1FAE GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾦ`, `ᾮ`],
    ],
    [
        // U+1F87 GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1F8F GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_A], `ᾇ`, `ᾏ`],
        // U+1F97 GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1F9F GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_H], `ᾗ`, `ᾟ`],
        // U+1FA7 GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI,
        // U+1FAF GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
        [[Key.KEY_V], `ᾧ`, `ᾯ`],
    ],
];

const MACRON: Space.Combo = [
    [Common.MACRON_KEY],
    [
        // U+00AF MACRON
        [[Common.MACRON_KEY], `¯`, false],

        // U+1FB1 GREEK SMALL LETTER ALPHA WITH MACRON,
        // U+1FB9 GREEK CAPITAL LETTER ALPHA WITH MACRON
        [[Key.KEY_A], `ᾱ`, `Ᾱ`],
        // U+1FD1 GREEK SMALL LETTER IOTA WITH MACRON,
        // U+1FD9 GREEK CAPITAL LETTER IOTA WITH MACRON
        [[Key.KEY_I], `ῑ`, `Ῑ`],
        // U+1FE1 GREEK SMALL LETTER UPSILON WITH MACRON,
        // U+1FE9 GREEK CAPITAL LETTER UPSILON WITH MACRON
        [[Key.KEY_U], `ῡ`, `Ῡ`],
    ],
    true,
];

const BREVE: Space.Combo = [
    [Common.BREVE_KEY],
    [
        // U+02D8 BREVE
        [[Common.BREVE_KEY], `˘`, false],

        // U+1FB0 GREEK SMALL LETTER ALPHA WITH VRACHY,
        // U+1FB8 GREEK CAPITAL LETTER ALPHA WITH VRACHY
        [[Key.KEY_A], `ᾰ`, `Ᾰ`],
        // U+1FD0 GREEK SMALL LETTER IOTA WITH VRACHY,
        // U+1FD8 GREEK CAPITAL LETTER IOTA WITH VRACHY
        [[Key.KEY_I], `ῐ`, `Ῐ`],
        // U+1FE0 GREEK SMALL LETTER UPSILON WITH VRACHY,
        // U+1FE8 GREEK CAPITAL LETTER UPSILON WITH VRACHY
        [[Key.KEY_U], `ῠ`, `Ῠ`],
    ],
    true,
];

export class Instance extends Layout.Instance
{
    constructor()
    {
        super(
            {
                language_name: Language.Name.GREEK,
                subset_name: `Polytonic`,
                is_language_default: false,
                combos_or_space: [
                    ...Common.LETTERS_AND_PUNCTUATION,

                    OXIA_AND_VARIA,
                    PERISPOMENI_AND_DIALYTIKA,
                    PSILI_AND_DASIA,
                    PSILI_OXIA_AND_DASIA_OXIA,
                    PSILI_VARIA_AND_DASIA_VARIA,
                    PSILI_PERISPOMENI_AND_DASIA_PERISPOMENI,
                    DIALYTIKA_OXIA_AND_DIALYTIKA_VARIA,
                    DIALYTIKA_PERISPOMENI,
                    [
                        [Common.IOTA_KEY],
                        [
                            IOTA,
                            OXIA_IOTA_AND_VARIA_IOTA,
                            PERISPOMENI_IOTA,
                            PSILI_IOTA_AND_DASIA_IOTA,
                            PSILI_OXIA_IOTA_AND_DASIA_OXIA_IOTA,
                            PSILI_VARIA_IOTA_AND_DASIA_VARIA_IOTA,
                            PSILI_PERISPOMENI_IOTA_AND_DASIA_PERISPOMENI_IOTA,
                            MACRON,
                            BREVE,
                        ],
                        true,
                    ],
                ],
            },
        );
    }
}
