export enum Name
{
    CARDO = `Cardo`,

    CATRINITY = `Catrinity`,

    EZRA = `Ezra`,
    EZRA_SR = `Ezra SR`,

    GALATIA = `Galatia`,

    GENTIUM = `Gentium`,
    GENTIUM_BOOK = `Gentium Book`,

    ORKNEY = `Orkney`,

    QUIVIRA = `Quivira`,

    NEAL_PALEO_HEBREW = `Neal - Paleo Hebrew`,

    UNIFRAKTUR_MAGUNTIA = `Unifraktur Maguntia`,

    ANCIENT_SEMETIC_ARAMAIC_EARLY_BR_RKB = `Ancient Semetic - Aramaic Early Br Rkb`,
    ANCIENT_SEMETIC_ARAMAIC_IMPERIAL_YEB = `Ancient Semetic - Aramaic Imperial Yeb`,
    ANCIENT_SEMETIC_ARAMAIC_VIIBCE = `Ancient Semetic - Aramaic VIIBCE`,
    ANCIENT_SEMETIC_HEBREW_ANCIENT = `Ancient Semetic - Hebrew Ancient`,
    ANCIENT_SEMETIC_HEBREW_LATE_BEN_KOSBA = `Ancient Semetic - Hebrew Late Ben-Kosba`,
    ANCIENT_SEMETIC_HEBREW_LATE_BET_SHEARIM = `Ancient Semetic - Hebrew Late Bet-Shearim`,
    ANCIENT_SEMETIC_HEBREW_LATE_HABAKKUK = `Ancient Semetic - Hebrew Late Habakkuk`,
    ANCIENT_SEMETIC_HEBREW_LATE_ISAIAH = `Ancient Semetic - Hebrew Late Isaiah`,
    ANCIENT_SEMETIC_HEBREW_MODERN_KETER_ARAM_TSOVA = `Ancient Semetic - Hebrew Modern Keter Aram Tsova`,
    ANCIENT_SEMETIC_HEBREW_MODERN_KETER_YG = `Ancient Semetic - Hebrew Modern Keter YG`,
    ANCIENT_SEMETIC_HEBREW_MODERN_MAKABI_YG = `Ancient Semetic - Hebrew Modern Makabi YG`,
    ANCIENT_SEMETIC_HEBREW_MODERN_SOFER_STAM_ASHKENAZ = `Ancient Semetic - Hebrew Modern Sofer Stam Ashkenaz`,
    ANCIENT_SEMETIC_HEBREW_PALEO_GEZER = `Ancient Semetic - Hebrew Paleo Gezer`,
    ANCIENT_SEMETIC_HEBREW_PALEO_LACHISH = `Ancient Semetic - Hebrew Paleo Lachish`,
    ANCIENT_SEMETIC_HEBREW_PALEO_MESHA = `Ancient Semetic - Hebrew Paleo Mesha`,
    ANCIENT_SEMETIC_HEBREW_PALEO_QUMRAN = `Ancient Semetic - Hebrew Paleo Qumran`,
    ANCIENT_SEMETIC_HEBREW_PALEO_SILOAM = `Ancient Semetic - Hebrew Paleo Siloam`,
    ANCIENT_SEMETIC_PHOENICIAN_AHIRAM = `Ancient Semetic - Phoenician Ahiram`,
    ANCIENT_SEMETIC_SAMARITAN = `Ancient Semetic - Samaritan`,

    KRIS_J_UDD_ARAMAIC_NABATAEAN = `Kris J. Udd - Aramaic Nabataean`,
    KRIS_J_UDD_GREEK_ARCHAIC = `Kris J. Udd - Greek Archaic`,
    KRIS_J_UDD_GREEK_COIN = `Kris J. Udd - Greek Coin`,
    KRIS_J_UDD_GREEK_NAHAL_HEVER_SCRIBE_A = `Kris J. Udd - Greek Nahal Hever Scribe A`,
    KRIS_J_UDD_GREEK_NAHAL_HEVER_SCRIBE_B = `Kris J. Udd - Greek Nahal Hever Scribe B`,
    KRIS_J_UDD_GREEK_PAPYRUS_P66 = `Kris J. Udd - Greek Papyrus P66`,
    KRIS_J_UDD_GREEK_PAPYRUS_P75 = `Kris J. Udd - Greek Papyrus P75`,
    KRIS_J_UDD_GREEK_ROSETTA_STONE = `Kris J. Udd - Greek Rosetta Stone`,
    KRIS_J_UDD_GREEK_SINAITICUS = `Kris J. Udd - Greek Sinaiticus`,
    KRIS_J_UDD_GREEK_THEODOTUS = `Kris J. Udd - Greek Theodotus`,
    KRIS_J_UDD_GREEK_WASHINGTONENSIS = `Kris J. Udd - Greek Washingtonensis`,
    KRIS_J_UDD_HEBREW_GEZER_CALENDAR = `Kris J. Udd - Hebrew Gezer Calendar`,
    KRIS_J_UDD_HEBREW_ISAIAH_SCROLL = `Kris J. Udd - Hebrew Isaiah Scroll`,
    KRIS_J_UDD_HEBREW_IVORY_POMEGRANATE = `Kris J. Udd - Hebrew Ivory Pomegranate`,
    KRIS_J_UDD_HEBREW_IZBET_SARTAH = `Kris J. Udd - Hebrew Izbet Sartah`,
    KRIS_J_UDD_HEBREW_KETEF_HINNOM_1 = `Kris J. Udd - Hebrew Ketef Hinnom 1`,
    KRIS_J_UDD_HEBREW_KETEF_HINNOM_2 = `Kris J. Udd - Hebrew Ketef Hinnom 2`,
    KRIS_J_UDD_HEBREW_LACHISH_3 = `Kris J. Udd - Hebrew Lachish 3`,
    KRIS_J_UDD_HEBREW_LACHISH_4 = `Kris J. Udd - Hebrew Lachish 4`,
    KRIS_J_UDD_HEBREW_LACHISH_5 = `Kris J. Udd - Hebrew Lachish 5`,
    KRIS_J_UDD_HEBREW_MOABITE_STONE = `Kris J. Udd - Hebrew Moabite Stone`,
    KRIS_J_UDD_HEBREW_PALEO = `Kris J. Udd - Hebrew Paleo`,
    KRIS_J_UDD_HEBREW_PROTO_SINAITIC_13 = `Kris J. Udd - Hebrew Proto-Sinaitic 13`,
    KRIS_J_UDD_HEBREW_PROTO_SINAITIC_15 = `Kris J. Udd - Hebrew Proto-Sinaitic 15`,
    KRIS_J_UDD_HEBREW_SAMARIA_OSTRACA = `Kris J. Udd - Hebrew Samaria Ostraca`,
    KRIS_J_UDD_HEBREW_SEALS = `Kris J. Udd - Hebrew Seals`,
    KRIS_J_UDD_HEBREW_SILOAM_STONE = `Kris J. Udd - Hebrew Siloam Stone`,
    KRIS_J_UDD_HEBREW_TEL_DAN = `Kris J. Udd - Hebrew Tel Dan`,
    KRIS_J_UDD_HEBREW_TEL_ZAYIT = `Kris J. Udd - Hebrew Tel Zayit`,
    KRIS_J_UDD_HEBREW_YAVNEH_YAM = `Kris J. Udd - Hebrew Yavneh Yam`,
    KRIS_J_UDD_SAMARITAN = `Kris J. Udd - Samaritan`,
    KRIS_J_UDD_UGARITIC = `Kris J. Udd - Ugaritic`,
}
