export { Instance } from "./data/instance.js";
export * as Books from "./data/books.js";
export * as Book from "./data/book.js";
export * as Languages from "./data/languages.js";
export * as Language from "./data/language.js";
export * as Versions from "./data/versions.js";
export * as Version from "./data/version.js";
export * as Files from "./data/files.js";
export * as File from "./data/file.js";
